### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by luckypoem** [qq906907952/go_proxy2#1]
hi.

on my mac:
cd $GOPATH
go get -u -v github.com/qq906907952/go_proxy2/src/go_proxy/
显示:
github.com/qq906907952/go_proxy2 (download)

# cd /Users/brite/go1.10.2/go/gopath/src/github.com/qq906907952/go_proxy2; git pull --ff-only
warning: no common commits
From https://github.com/qq906907952/go_proxy2
 + b7e5df0...eda3f8d master     -> origin/master  (forced update)
 * [new tag]         linux      -> linux
 * [new tag]         osx        -> osx
fatal: Not possible to fast-forward, aborting.
package github.com/qq906907952/go_proxy2/src/go_proxy: exit status 128

怎么解决错误？

**Comment by qq906907952** [comment]
这个我也不知道什么原因耶 我是在linux交叉编译过去的 而且编译到mac上要改改代码。mac的bin你可以直接去release下载。

**Comment by briteming** [comment]
不错。很好用。谢谢
